server:
    port: 8080
    servlet:
      context-path: /apps-portal
    session:
      cookie:
        name: UISESSION
security:
  basic:
    enabled: falsez
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/auth/user/me

spring:
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl      

 