server:
    port: 8000

spring:
    h2:
      console:
        enabled: true
        path: /h2-console
    datasource:
      url: jdbc:h2:./data/demo
      username: sa  
      password: password 

   

 